server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: "prod"  # Default setting. This can also be set by the Configserver.
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: 'root'
  jpa:
    show-sql: true
  sql:
    init:
      mode: always  # Always execute the schema.sql script
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
